version: '3.8'
services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    environment:
      NODE_ENV: "production"
    depends_on:
      - database
      - redis
    networks:
      - app_network
    restart: always

  database:
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d my_database"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    environment:
      REDIS_PASSWORD: "redispass123"
    command: redis-server --requirepass $${REDIS_PASSWORD}
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: always

volumes:
  pg_data:
    driver: local

networks:
  app_network:
    driver: bridge
